[versions]
kotlin = "2.0.0"

minecraft = "1.21"
qfapi = "11.0.0-alpha.3+0.100.7-1.21"
qkl = "2.1.0+kt.1.8.22+flk.1.9.4" # https://github.com/QuiltMC/quilt-kotlin-libraries/pull/98
loader = "0.26.4-beta.1"
mappings = "1.21+build.18"
loom = "1.7.4"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
qfapi = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "qfapi" }
qfapi_deprecated = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api-deprecated", version.ref = "qfapi" }


qkl = { module = "org.quiltmc.quilt-kotlin-libraries:quilt-kotlin-libraries", version.ref = "qkl" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "loader" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "mappings" }

[bundles]
quilted_fabric_api = ["qfapi", "qfapi_deprecated"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
quilt_loom = { id = "org.quiltmc.loom", version.ref = "loom" }
